// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ERRORCODE_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_ERRORCODE_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {

struct ErrorCode;

enum Err {
  Err_NO_SUCH_FILE = 0,
  Err_MIN = Err_NO_SUCH_FILE,
  Err_MAX = Err_NO_SUCH_FILE
};

inline const Err (&EnumValuesErr())[1] {
  static const Err values[] = {
    Err_NO_SUCH_FILE
  };
  return values;
}

inline const char * const *EnumNamesErr() {
  static const char * const names[] = {
    "NO_SUCH_FILE",
    nullptr
  };
  return names;
}

inline const char *EnumNameErr(Err e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesErr()[index];
}

struct ErrorCode FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_CODE = 4
  };
  Err Code() const {
    return static_cast<Err>(GetField<int16_t>(VT_CODE, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_CODE) &&
           verifier.EndTable();
  }
};

struct ErrorCodeBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Code(Err Code) {
    fbb_.AddElement<int16_t>(ErrorCode::VT_CODE, static_cast<int16_t>(Code), 0);
  }
  explicit ErrorCodeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ErrorCodeBuilder &operator=(const ErrorCodeBuilder &);
  flatbuffers::Offset<ErrorCode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ErrorCode>(end);
    return o;
  }
};

inline flatbuffers::Offset<ErrorCode> CreateErrorCode(
    flatbuffers::FlatBufferBuilder &_fbb,
    Err Code = Err_NO_SUCH_FILE) {
  ErrorCodeBuilder builder_(_fbb);
  builder_.add_Code(Code);
  return builder_.Finish();
}

inline const Protocol::ErrorCode *GetErrorCode(const void *buf) {
  return flatbuffers::GetRoot<Protocol::ErrorCode>(buf);
}

inline const Protocol::ErrorCode *GetSizePrefixedErrorCode(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<Protocol::ErrorCode>(buf);
}

inline bool VerifyErrorCodeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Protocol::ErrorCode>(nullptr);
}

inline bool VerifySizePrefixedErrorCodeBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Protocol::ErrorCode>(nullptr);
}

inline void FinishErrorCodeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Protocol::ErrorCode> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedErrorCodeBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<Protocol::ErrorCode> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_ERRORCODE_PROTOCOL_H_
