// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNCHRONISM_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_SYNCHRONISM_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

namespace Protocol {

struct FilePath;

struct BlockInfo;

struct SyncFileList;

struct FileDigest;

struct FileRebuildInfo;

struct FileRebuildChunk;

struct FilePath FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SRCPATH = 4,
    VT_DESPATH = 6
  };
  const flatbuffers::String *SrcPath() const {
    return GetPointer<const flatbuffers::String *>(VT_SRCPATH);
  }
  const flatbuffers::String *DesPath() const {
    return GetPointer<const flatbuffers::String *>(VT_DESPATH);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SRCPATH) &&
           verifier.Verify(SrcPath()) &&
           VerifyOffset(verifier, VT_DESPATH) &&
           verifier.Verify(DesPath()) &&
           verifier.EndTable();
  }
};

struct FilePathBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_SrcPath(flatbuffers::Offset<flatbuffers::String> SrcPath) {
    fbb_.AddOffset(FilePath::VT_SRCPATH, SrcPath);
  }
  void add_DesPath(flatbuffers::Offset<flatbuffers::String> DesPath) {
    fbb_.AddOffset(FilePath::VT_DESPATH, DesPath);
  }
  explicit FilePathBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FilePathBuilder &operator=(const FilePathBuilder &);
  flatbuffers::Offset<FilePath> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FilePath>(end);
    return o;
  }
};

inline flatbuffers::Offset<FilePath> CreateFilePath(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> SrcPath = 0,
    flatbuffers::Offset<flatbuffers::String> DesPath = 0) {
  FilePathBuilder builder_(_fbb);
  builder_.add_DesPath(DesPath);
  builder_.add_SrcPath(SrcPath);
  return builder_.Finish();
}

inline flatbuffers::Offset<FilePath> CreateFilePathDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *SrcPath = nullptr,
    const char *DesPath = nullptr) {
  return Protocol::CreateFilePath(
      _fbb,
      SrcPath ? _fbb.CreateString(SrcPath) : 0,
      DesPath ? _fbb.CreateString(DesPath) : 0);
}

struct BlockInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_OFFSET = 4,
    VT_LENGTH = 6,
    VT_CHECKSUM = 8,
    VT_MD5 = 10
  };
  int64_t Offset() const {
    return GetField<int64_t>(VT_OFFSET, 0);
  }
  int32_t Length() const {
    return GetField<int32_t>(VT_LENGTH, 0);
  }
  uint32_t Checksum() const {
    return GetField<uint32_t>(VT_CHECKSUM, 0);
  }
  const flatbuffers::String *Md5() const {
    return GetPointer<const flatbuffers::String *>(VT_MD5);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_OFFSET) &&
           VerifyField<int32_t>(verifier, VT_LENGTH) &&
           VerifyField<uint32_t>(verifier, VT_CHECKSUM) &&
           VerifyOffset(verifier, VT_MD5) &&
           verifier.Verify(Md5()) &&
           verifier.EndTable();
  }
};

struct BlockInfoBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Offset(int64_t Offset) {
    fbb_.AddElement<int64_t>(BlockInfo::VT_OFFSET, Offset, 0);
  }
  void add_Length(int32_t Length) {
    fbb_.AddElement<int32_t>(BlockInfo::VT_LENGTH, Length, 0);
  }
  void add_Checksum(uint32_t Checksum) {
    fbb_.AddElement<uint32_t>(BlockInfo::VT_CHECKSUM, Checksum, 0);
  }
  void add_Md5(flatbuffers::Offset<flatbuffers::String> Md5) {
    fbb_.AddOffset(BlockInfo::VT_MD5, Md5);
  }
  explicit BlockInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  BlockInfoBuilder &operator=(const BlockInfoBuilder &);
  flatbuffers::Offset<BlockInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<BlockInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<BlockInfo> CreateBlockInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t Offset = 0,
    int32_t Length = 0,
    uint32_t Checksum = 0,
    flatbuffers::Offset<flatbuffers::String> Md5 = 0) {
  BlockInfoBuilder builder_(_fbb);
  builder_.add_Offset(Offset);
  builder_.add_Md5(Md5);
  builder_.add_Checksum(Checksum);
  builder_.add_Length(Length);
  return builder_.Finish();
}

inline flatbuffers::Offset<BlockInfo> CreateBlockInfoDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t Offset = 0,
    int32_t Length = 0,
    uint32_t Checksum = 0,
    const char *Md5 = nullptr) {
  return Protocol::CreateBlockInfo(
      _fbb,
      Offset,
      Length,
      Checksum,
      Md5 ? _fbb.CreateString(Md5) : 0);
}

struct SyncFileList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_LIST = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<FilePath>> *List() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<FilePath>> *>(VT_LIST);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LIST) &&
           verifier.Verify(List()) &&
           verifier.VerifyVectorOfTables(List()) &&
           verifier.EndTable();
  }
};

struct SyncFileListBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_List(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<FilePath>>> List) {
    fbb_.AddOffset(SyncFileList::VT_LIST, List);
  }
  explicit SyncFileListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SyncFileListBuilder &operator=(const SyncFileListBuilder &);
  flatbuffers::Offset<SyncFileList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SyncFileList>(end);
    return o;
  }
};

inline flatbuffers::Offset<SyncFileList> CreateSyncFileList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<FilePath>>> List = 0) {
  SyncFileListBuilder builder_(_fbb);
  builder_.add_List(List);
  return builder_.Finish();
}

inline flatbuffers::Offset<SyncFileList> CreateSyncFileListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<FilePath>> *List = nullptr) {
  return Protocol::CreateSyncFileList(
      _fbb,
      List ? _fbb.CreateVector<flatbuffers::Offset<FilePath>>(*List) : 0);
}

struct FileDigest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_PATH = 4,
    VT_TASKID = 6,
    VT_SPLITSIZE = 8,
    VT_INFOS = 10
  };
  const FilePath *Path() const {
    return GetPointer<const FilePath *>(VT_PATH);
  }
  uint32_t TaskID() const {
    return GetField<uint32_t>(VT_TASKID, 0);
  }
  uint32_t Splitsize() const {
    return GetField<uint32_t>(VT_SPLITSIZE, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<BlockInfo>> *Infos() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<BlockInfo>> *>(VT_INFOS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PATH) &&
           verifier.VerifyTable(Path()) &&
           VerifyField<uint32_t>(verifier, VT_TASKID) &&
           VerifyField<uint32_t>(verifier, VT_SPLITSIZE) &&
           VerifyOffset(verifier, VT_INFOS) &&
           verifier.Verify(Infos()) &&
           verifier.VerifyVectorOfTables(Infos()) &&
           verifier.EndTable();
  }
};

struct FileDigestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_Path(flatbuffers::Offset<FilePath> Path) {
    fbb_.AddOffset(FileDigest::VT_PATH, Path);
  }
  void add_TaskID(uint32_t TaskID) {
    fbb_.AddElement<uint32_t>(FileDigest::VT_TASKID, TaskID, 0);
  }
  void add_Splitsize(uint32_t Splitsize) {
    fbb_.AddElement<uint32_t>(FileDigest::VT_SPLITSIZE, Splitsize, 0);
  }
  void add_Infos(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<BlockInfo>>> Infos) {
    fbb_.AddOffset(FileDigest::VT_INFOS, Infos);
  }
  explicit FileDigestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FileDigestBuilder &operator=(const FileDigestBuilder &);
  flatbuffers::Offset<FileDigest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FileDigest>(end);
    return o;
  }
};

inline flatbuffers::Offset<FileDigest> CreateFileDigest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<FilePath> Path = 0,
    uint32_t TaskID = 0,
    uint32_t Splitsize = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<BlockInfo>>> Infos = 0) {
  FileDigestBuilder builder_(_fbb);
  builder_.add_Infos(Infos);
  builder_.add_Splitsize(Splitsize);
  builder_.add_TaskID(TaskID);
  builder_.add_Path(Path);
  return builder_.Finish();
}

inline flatbuffers::Offset<FileDigest> CreateFileDigestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<FilePath> Path = 0,
    uint32_t TaskID = 0,
    uint32_t Splitsize = 0,
    const std::vector<flatbuffers::Offset<BlockInfo>> *Infos = nullptr) {
  return Protocol::CreateFileDigest(
      _fbb,
      Path,
      TaskID,
      Splitsize,
      Infos ? _fbb.CreateVector<flatbuffers::Offset<BlockInfo>>(*Infos) : 0);
}

struct FileRebuildInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TASKID = 4,
    VT_LENGTH = 6
  };
  uint32_t TaskID() const {
    return GetField<uint32_t>(VT_TASKID, 0);
  }
  uint64_t Length() const {
    return GetField<uint64_t>(VT_LENGTH, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TASKID) &&
           VerifyField<uint64_t>(verifier, VT_LENGTH) &&
           verifier.EndTable();
  }
};

struct FileRebuildInfoBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_TaskID(uint32_t TaskID) {
    fbb_.AddElement<uint32_t>(FileRebuildInfo::VT_TASKID, TaskID, 0);
  }
  void add_Length(uint64_t Length) {
    fbb_.AddElement<uint64_t>(FileRebuildInfo::VT_LENGTH, Length, 0);
  }
  explicit FileRebuildInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FileRebuildInfoBuilder &operator=(const FileRebuildInfoBuilder &);
  flatbuffers::Offset<FileRebuildInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FileRebuildInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<FileRebuildInfo> CreateFileRebuildInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TaskID = 0,
    uint64_t Length = 0) {
  FileRebuildInfoBuilder builder_(_fbb);
  builder_.add_Length(Length);
  builder_.add_TaskID(TaskID);
  return builder_.Finish();
}

struct FileRebuildChunk FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_TASKID = 4,
    VT_OFFSET = 6,
    VT_LENGTH = 8,
    VT_ISMD5 = 10,
    VT_DATA = 12
  };
  uint32_t TaskID() const {
    return GetField<uint32_t>(VT_TASKID, 0);
  }
  int64_t Offset() const {
    return GetField<int64_t>(VT_OFFSET, 0);
  }
  int32_t Length() const {
    return GetField<int32_t>(VT_LENGTH, 0);
  }
  bool IsMd5() const {
    return GetField<uint8_t>(VT_ISMD5, 0) != 0;
  }
  const flatbuffers::String *Data() const {
    return GetPointer<const flatbuffers::String *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TASKID) &&
           VerifyField<int64_t>(verifier, VT_OFFSET) &&
           VerifyField<int32_t>(verifier, VT_LENGTH) &&
           VerifyField<uint8_t>(verifier, VT_ISMD5) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.Verify(Data()) &&
           verifier.EndTable();
  }
};

struct FileRebuildChunkBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_TaskID(uint32_t TaskID) {
    fbb_.AddElement<uint32_t>(FileRebuildChunk::VT_TASKID, TaskID, 0);
  }
  void add_Offset(int64_t Offset) {
    fbb_.AddElement<int64_t>(FileRebuildChunk::VT_OFFSET, Offset, 0);
  }
  void add_Length(int32_t Length) {
    fbb_.AddElement<int32_t>(FileRebuildChunk::VT_LENGTH, Length, 0);
  }
  void add_IsMd5(bool IsMd5) {
    fbb_.AddElement<uint8_t>(FileRebuildChunk::VT_ISMD5, static_cast<uint8_t>(IsMd5), 0);
  }
  void add_Data(flatbuffers::Offset<flatbuffers::String> Data) {
    fbb_.AddOffset(FileRebuildChunk::VT_DATA, Data);
  }
  explicit FileRebuildChunkBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FileRebuildChunkBuilder &operator=(const FileRebuildChunkBuilder &);
  flatbuffers::Offset<FileRebuildChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FileRebuildChunk>(end);
    return o;
  }
};

inline flatbuffers::Offset<FileRebuildChunk> CreateFileRebuildChunk(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TaskID = 0,
    int64_t Offset = 0,
    int32_t Length = 0,
    bool IsMd5 = false,
    flatbuffers::Offset<flatbuffers::String> Data = 0) {
  FileRebuildChunkBuilder builder_(_fbb);
  builder_.add_Offset(Offset);
  builder_.add_Data(Data);
  builder_.add_Length(Length);
  builder_.add_TaskID(TaskID);
  builder_.add_IsMd5(IsMd5);
  return builder_.Finish();
}

inline flatbuffers::Offset<FileRebuildChunk> CreateFileRebuildChunkDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t TaskID = 0,
    int64_t Offset = 0,
    int32_t Length = 0,
    bool IsMd5 = false,
    const char *Data = nullptr) {
  return Protocol::CreateFileRebuildChunk(
      _fbb,
      TaskID,
      Offset,
      Length,
      IsMd5,
      Data ? _fbb.CreateString(Data) : 0);
}

}  // namespace Protocol

#endif  // FLATBUFFERS_GENERATED_SYNCHRONISM_PROTOCOL_H_
